import {ENV} from 'app/services';

export default {
    PAGINATION_SIZE: ENV.PAGINATION_SIZE,
    INTERACTIONS_URI: ENV.INTERACTIONS_URI,
    MESSAGES_URI: ENV.MESSAGES_URI,
    REPLY_OFFCONTACT_URI: ENV.REPLY_OFFCONTACT_URI,
    SEND_CHAT_VIA_EMAIL: ENV.SEND_CHAT_VIA_EMAIL,
    CUSTOMER_HISTORY_URI: ENV.CUSTOMER_HISTORY_URI,
    TRANSFER_URI: ENV.TRANSFER_URI,
    WEBHOOK_URI: ENV.WEBHOOK_URI,
    RDSTATION_URI: ENV.RDSTATION_URI,
    DISCARD_OFFCONTACT_URI: ENV.DISCARD_OFFCONTACT_URI,
    INTERACTION_COUNT_URI: ENV.INTERACTION_COUNT_URI,
    AGENT_HISTORY_URI: ENV.BODYLIFT + '/interactions',
    REPORTS: ENV.REPORTS + '/report-data'
};
