import {ENV} from 'app/services';

export default {
    VISITORS_URI: ENV.VISITORS_URI,
    VISITOR_DETAIL_URI: ENV.VISITOR_DETAIL_URI,
    VISITOR_INVITE_URI: ENV.VISITOR_INVITE_URI,
    VISITOR_MESSAGE_URI: ENV.VISITOR_MESSAGE_URI,
    REPORTS: ENV.REPORTS + '/report-data'
};
