import {ENV} from 'app/services';

export default {
    PROCESSKEY_URI: ENV.PROCESSKEY_URI,
    CUSTOMERS_URI: ENV.CUSTOMERS_URI,
    TAGS_URI: ENV.TAGS_URI,
    NOTES_URI: ENV.NOTES_URI,
    MEDIA_UPLOAD_URI: ENV.MEDIA_UPLOAD_URI,
    MELI_MSG_URI: ENV.REPLY_OFFCONTACT_URI,
    FINISH_MELIMSG: ENV.CUSTOMER_HISTORY_URI
};
